[package]
name = "lintbook-rules"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bincode = { version = "2.0.1", features = ["serde"] }
datafox.workspace = true
hex = { workspace = true }
lintbook-config = { path = "../lintbook-config" }
lintbook-core = { path = "../lintbook-core" }
lintbook-lang = { path = "../lintbook-lang" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-rust = { workspace = true }

[dev-dependencies]
tempfile = "3.0"
