[package]
name = "treelint-scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
treelint-lang = { path = "../treelint-lang" }
treelint-core = { path = "../treelint-core" }
treelint-config = { path = "../treelint-config" }
anyhow = { workspace = true }
tree-sitter = { workspace = true }
serde = { workspace = true }
ignore = "0.4"
num_cpus = "1.16"

[dev-dependencies]
tempfile = "3.0"
