[package]
name = "treelint-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-elixir = { workspace = true }
tree-sitter-python = { workspace = true }
tree-sitter-rust = { workspace = true }
tree-sitter-sequel = { workspace = true }
treelint-config = { path = "../treelint-config" }
treelint-core = { path = "../treelint-core" }
treelint-lang-elixir = { path = "../treelint-lang-elixir" }
treelint-lang-python = { path = "../treelint-lang-python" }
treelint-lang-rust = { path = "../treelint-lang-rust" }
treelint-lang-sql = { path = "../treelint-lang-sql" }
